name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '20.2.0.java8'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.1.469'
      - run: gu install native-image
      - run: clojure -A:native-image
        env:
          GRAALVM_HOME: '/opt/hostedtoolcache/GraalVM/20.2.0-java8/x64'
      
