name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '20.2.0.java8'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.1.469'
      - run: clojure -A:uberjar --main-class core
      - run: java -agentlib:native-image-agent=config-output-dir=temp -jar target/core.jar
      - run: clojure -A:native-image
      
